version: '3'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto-broker
    ports:
    - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./moquitto/data:/moquitto/data
      - ./moquitto/log:/moquitto/log
  
  simulador-iot:
    build: ./radar
    container_name: simulador-iot
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=8883
    depends_on:
      - mqtt-broker

  servico-radar:
    build: ./servico-radar
    container_name: servico-radar
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_HOST=8883
    depends_on:
    - mqtt-broker