
services:

  init_db:
    build: ./init_db
    env_file:
      - .env
    restart: "no"
    
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto
    ports:
      - '8883:8883'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
    environment:
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=senhaLeitura
    command: >
      sh -c "
      chmod -R 0600 /mosquitto/config/password.txt
      && exec mosquitto -c /mosquitto/config/mosquitto.conf
      "

  simulador-radar:
    build: ./simulador_radar
    container_name: simulador-radar
    environment:
      - MOSQUITTO_HOST=mosquitto
      - MOSQUITTO_TOPIC=speed-reading
      - MOSQUITTO_PORT=8883
      - THREAD_COUNT=3
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=senhaLeitura
    depends_on:
      - mosquitto
    volumes:
      - ./simulador_radar/logs/logs.log:/app/logs/logs.log

  servico-multas:
    build: ./servico_multas
    container_name: servico_multas
    hostname: servico-multas
    ports:
      - "5000:5000"
    environment:
      - MULTAS_GRPC_PORT=50051
      - DB_SALT=multas
    env_file:
      - .env
    volumes:
      - ./servico_multas/logs/logs.log:/app/logs/logs.log

  servico-leituras:
    build: ./servico_leituras
    container_name: servico-leituras
    ports:
      - "50051:50051"
    environment:
      - MOSQUITTO_HOST=mosquitto
      - MOSQUITTO_TOPIC=speed-reading
      - MOSQUITTO_PORT=8883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=senhaLeitura
      - MONGO_DB=letiuras_velocidade
      - MULTAS_SERVER=servico_multas
      - MULTAS_PORT=50051
    env_file:
      - .env
    depends_on:
      - mosquitto
      - servico-multas
    volumes:
     - ./servico_leituras/logs/logs.log:/app/logs/logs.log
      
  app-usuario:
    build: ./app_usuario
    container_name: app-usuario
    hostname: app-usuario
    ports:
      - 8000:8000
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=notificacao
      - API_MULTAS=http://servico-multas:5000
      - FLASK_SECRET_KEY=secret-key-123
    depends_on:
      - servico-multas
