
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    ports:
      - '8883:8883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  # rabbitmq:
  #   image: rabbitmq:4.4.1-management
  #   ports:
  #   - "5672:5672"
  #   - "15672:15672" #UI de gerenciamento 
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  #     - RABBITMQ_DEFAULT_VHOST=/
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq

  simulador-radar:
    build: ./simulador_radar
    container_name: simulador-radar
    environment:
      - MOSQUITTO_HOST=mosquitto
      - MOSQUITTO_TOPIC=speed-reading
      - MOSQUITTO_PORT=8883
      - THREAD_COUNT=3
    depends_on:
      - mosquitto
    volumes:
      - ./simulador_radar/logs/logs.log:/app/logs/logs.log

  servico-multas:
    build: ./servico_multas
    container_name: servico_multas
    hostname: servico-multas
    ports:
      - "5000:5000"
    environment:
      - SERVICO_LEITURAS_HOST=servico-leituras
      - SERVICO_LEITURAS_PORT=50051
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=notifications
      - DB_SALT=multas
    volumes:
      - ./servico_multas/logs/logs.log:/app/logs/logs.log

  servico-leituras:
    build: ./servico_leituras
    container_name: servico-leituras
    ports:
      - "50051:50051"
      - "5000:5000"
    environment:
      - MOSQUITTO_HOST=mosquitto
      - MOSQUITTO_TOPIC=speed-reading
      - MOSQUITTO_PORT=8883
      - MONGO_DB=letiuras_velocidade
      - MULTAS_SERVER=servico_multas
      - MULTAS_PORT=50051
    depends_on:
      # - mosquitto
      - servico-multas
    volumes:
     - ./servico_leituras/logs/logs.log:/app/logs/logs.log
      
  # servico-notificacao:
  #   build: ./servico_notificacao
  #   container_name: servico_notificacao
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_QUEUE=notificacao
  #   depends_on:
  #     - rabbitmq
  
  app-usuario:
    build: ./app_usuario
    container_name: app-usuario
    hostname: app-usuario
    ports:
      - 8000:8000
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=notificacao
      - API_MULTAS=http://servico-multas:5000
      - FLASK_SECRET_KEY=secret-key-123
    depends_on:
      - servico-multas
